#!/bin/bash
clearVars() {
    unset ARG ARGS res
}

cleanUp() {
    msg="all cleaned up!!"
    magenta "\t\t${msg^^}\n\n"
    
}

gracefulExit() {
    clearVars
    cleanUp
    exit 0
}

cleanExit() {
    clearVars
    exit 0
}

exitProg() {
    clearVars
    exit 121
}

synopsis() {
    clear
    printf "Program file: %s\n\n%s's home: %s\n\n" "chromepwds" "chromepwds" "~/bin"
    printf "Synopsis: chromepwds <[ option ]>\n\n"
    printf "Options:\n\t? = Display this manual\n\tl = List the CSV files location\n\tc = Search the given CSV file for given term\n\to = Search the latest CSV file for given term\n\n"
    printf "Examples:\n"
    printf "\tchromepwds -?\n\n"
    printf "\tchromepwds -l\n\n"
    printf "\tchromepwds -c <[ 0-N _ ]> google\n\n"
    printf "\tchromepwds -o google\n\n"
}

trap "gracefulExit" INT TERM QUIT STOP KILL

while getopts ':?lc:o:' OPTION; do
    case ${OPTION} in
        l)
            # list all CSV file in the ~/Documents/information directory
            printf "\nThe CSV files live at: %s\n" "~/Documents/information/chromepasswords"
            ls -lh ~/Documents/information | grep ".*\.csv"
            cleanExit
        ;;
        
        o)
            # Search term within the latest CSV file
            # 2nd param = search term
            if [[ $# -lt 2 ]];
            then
                exitProg
            else
                TERM=$2
                # printf '\tSearch Term: %s\n' ${TERM^^}
                res=$(sed -n '2,$p' ~/Documents/information/chromepasswords/ChromePasswords_.csv | awk "/${TERM}/" | awk '{gsub(/[ \t]/,",");print}' | awk -F ',' '{print "URL:",$1, " Username:",$2, " Password:", $3;}')
                
                if [[ $str != $res ]];
                then
                    printf '\tSearch Term: %s\n' ${TERM^^}
                    printf '%s\n' "${res}"
                fi
            fi
            cleanExit
        ;;
        
        c)
            # Search term within given CSV file
            # 2nd param = file name last character e.g. (0 - 6 and _)
            # 3rd param = search term
            if [[ $# -eq 3 ]];
            then
                FILE_NAME="ChromePasswords${2}.csv"
                FILE_PATH=~/Documents/information/chromepasswords/$FILE_NAME
                TERM=$3
                # printf 'parameters: %s %s\nfile name: %s\nfile path: %s\n' $2, $3, $FILE_NAME, $FILE_PATH
                # ls -lhmnogs $FILE_PATH
                
                res=$(sed -n '2,$p' $FILE_PATH | awk "/${TERM}/" | awk '{gsub(/[ \t]/,",");print}' | awk -F ',' '{print "URL:",$1, " Username:",$3, " Password:", $4;}')
                if [[ $str != $res ]];
                then
                    printf '\tSearch Term: %s\n' ${TERM^^}
                    printf '%s\n' "${res}"
                else
                    exitProg
                fi
            else
                exitProg
            fi
            cleanExit
        ;;
        
        :)
            exitProg
        ;;
        
        \?)
            synopsis
        ;;
    esac
done
shift "$(($OPTIND -1))"

if [ $# -gt 0 ];
then
    unset $@
fi
